# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo:latest
    ports:
        - "27017:27017"
    container_name: albatross_db
    volumes:
      - ./data:/data/db
